/*
 * DAPManagementJPanel.java
 *
 * Created on 28. Februar 2005, 11:19
 */

package org.dyndns.widerstand.openplatformmanager;

/**
 *
 * @author  Widerstand
 */
public class DAPManagementJPanel extends javax.swing.JPanel {
    
    private MainJFrame parent;
    
    /** Creates new form DAPManagementJPanel */
    public DAPManagementJPanel(MainJFrame parent) {
        this.parent = parent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelToken = new TokenJPanel(parent);
        jPanelDAP = new DAPJPanel(parent);
        jPanelValidateReceiptDAP = new ValidateDAPJPanel(parent);

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("Manage Data Authentication Patterns"), new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5))));
        jTabbedPane1.addTab("Calculate Token", jPanelToken);

        jTabbedPane1.addTab("Load File Data Block DAP", jPanelDAP);

        jTabbedPane1.addTab("Validate Receipt DAP", jPanelValidateReceiptDAP);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public void refresh() {
       ((DAPJPanel)jPanelDAP).refresh();
       ((TokenJPanel)jPanelToken).refresh();
       ((ValidateDAPJPanel)jPanelValidateReceiptDAP).refresh();
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelDAP;
    private javax.swing.JPanel jPanelToken;
    private javax.swing.JPanel jPanelValidateReceiptDAP;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
