/*
 * KeyManagementJPanel.java
 *
 * Created on 23. Februar 2005, 07:28
 */

package org.dyndns.widerstand.openplatformmanager;

/**
 *
 * @author  Widerstand
 */
public class KeyManagementJPanel extends javax.swing.JPanel {
    
    private MainJFrame parent;
    
    /** Creates new form KeyManagementJPanel */
    public KeyManagementJPanel(MainJFrame parent) {
        this.parent = parent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new PutKeySetJPanel(parent);
        jPanel2 = new PutKeyJPanel(parent);
        jPanel3 = new DeleteKeyJPanel(parent);
        jPanel4 = new PINJPanel(parent);

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("Key Management"), new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5))));
        jTabbedPane1.addTab("Put Key Set", jPanel1);

        jTabbedPane1.addTab("Put Key", jPanel2);

        jTabbedPane1.addTab("Delete Key", jPanel3);

        jTabbedPane1.addTab("PIN", jPanel4);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
