/*
 * ConnectionManagementJPanel.java
 *
 * Created on 26. März 2005, 20:35
 */

package org.dyndns.widerstand.openplatformmanager;

/**
 *
 * @author  Widerstand
 */
public class ConnectionManagementJPanel extends javax.swing.JPanel {
    
    private MainJFrame parent;
    
    /** Creates new form ConnectionManagementJPanel */
    public ConnectionManagementJPanel(MainJFrame parent) {
        this.parent = parent;
        initComponents();
        jTabbedPane1.setEnabledAt(getComponentIndex("Connect"), false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelContext = new ContextJPanel(parent);
        jPanelConnect = new ConnectJPanel(parent);

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("Manage Connection"), new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5))));
        jTabbedPane1.addTab("Context", jPanelContext);

        jTabbedPane1.addTab("Connect", jPanelConnect);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    public void enableAfterEstablishContext() {
        ((ConnectJPanel)jPanelConnect).enableAfterEstablishContext();
        ((ContextJPanel)jPanelContext).enableAfterEstablishContext();
        jTabbedPane1.setEnabledAt(getComponentIndex("Connect"), true);
        jTabbedPane1.setSelectedIndex(getComponentIndex("Connect"));
    }
    
    public void enableAfterConnect() {
        ((ConnectJPanel)jPanelConnect).enableAfterConnect();
    }
    
    public void disableAfterDisconnect() {
        ((ConnectJPanel)jPanelConnect).disableAfterDisconnect();
    }
    
    public void disableAfterReleaseContext() {
        ((ContextJPanel)jPanelContext).disableAfterReleaseContext();
        jTabbedPane1.setEnabledAt(getComponentIndex("Connect"), false);
        jTabbedPane1.setSelectedIndex(getComponentIndex("Context"));
    }
    
    private int getComponentIndex(String id) {
        for (int i=0; i<jTabbedPane1.getTabCount(); i++) {
            if (jTabbedPane1.getTitleAt(i).equals(id)) {
                return i;
            }
        }
        return -1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelConnect;
    private javax.swing.JPanel jPanelContext;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
