/*
 * ContextJPanel.java
 *
 * Created on 26. März 2005, 20:08
 */

package org.dyndns.widerstand.openplatformmanager;

import javax.swing.JPanel;
import javax.swing.ImageIcon;
import java.awt.GridBagLayout;
import java.awt.Graphics;
import java.awt.Image;
import org.dyndns.widerstand.OpenPlatform.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;

/**
 *
 * @author  Widerstand
 */
public class ContextJPanel extends javax.swing.JPanel {
    
    private MainJFrame parent;
    
    /** Creates new form ContextJPanel */
    public ContextJPanel(MainJFrame parent) {
        this.parent = parent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = createImageJPanel();
        jButtonEstablishContext = new javax.swing.JButton();
        jButtonReleaseContext = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("Establish Context"), new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5))));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonEstablishContext.setText("Establish Context");
        jButtonEstablishContext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstablishContextActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 5, 5);
        jPanel1.add(jButtonEstablishContext, gridBagConstraints);

        jButtonReleaseContext.setText("Release Context");
        jButtonReleaseContext.setEnabled(false);
        jButtonReleaseContext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReleaseContextActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 5, 5);
        jPanel1.add(jButtonReleaseContext, gridBagConstraints);

        jPanel2.add(jPanel1, new java.awt.GridBagConstraints());

        jScrollPane1.setViewportView(jPanel2);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    private void jButtonReleaseContextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReleaseContextActionPerformed
        try {
            if (parent.session.cardHandle != 0) {
                OPSPWrapper.cardDisconnect(parent.session.cardHandle);
            }
            OPSPWrapper.releaseContext(parent.session.cardContext);
        } catch (OPSPException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Open Platform Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        parent.session = new SessionInformation();
        parent.disableAfterReleaseContext();
    }//GEN-LAST:event_jButtonReleaseContextActionPerformed
    
    private void jButtonEstablishContextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstablishContextActionPerformed
        String[] readers;
        long cardContext;
        try {
            cardContext = OPSPWrapper.establishContext();
            readers = OPSPWrapper.listReaders(cardContext);
        } catch (OPSPException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Open Platform Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        parent.session = new SessionInformation();
        parent.session.cardContext = cardContext;
        for (String reader : readers) {
            parent.session.readers.add(reader);
        }
        parent.enableAfterEstablishContext();
    }//GEN-LAST:event_jButtonEstablishContextActionPerformed
    
    public void enableAfterEstablishContext() {
        jButtonReleaseContext.setEnabled(true);
        jButtonEstablishContext.setEnabled(false);
    }
    
    public void disableAfterReleaseContext() {
        jButtonReleaseContext.setEnabled(false);
        jButtonEstablishContext.setEnabled(true);
    }
    
    public JPanel createImageJPanel() {
        JPanel panel;
        try {
            final String imageName = "OpenPlatformManager.jpg";
            final BufferedImage image = ImageIO.read(this.getClass().getResource(imageName));
            int paneHeight = image.getHeight();
            int paneWidth = image.getWidth();
            final java.awt.Dimension dim = new java.awt.Dimension(paneWidth, paneHeight);
            panel = new JPanel() {                

                public void paintComponent(Graphics g) {
                    g.drawImage(image, 0, 0, this);
                    super.paintComponent(g);
                }
            };
            panel.setOpaque(false);
            panel.setVisible(true);            
            panel.setSize(dim);
            panel.setMinimumSize(dim);
            panel.setPreferredSize(dim);
            panel.setMaximumSize(dim);
        } catch (IOException e) {
            return new JPanel();
        }
        return panel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEstablishContext;
    private javax.swing.JButton jButtonReleaseContext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
