/*
 * PutKeyJPanel.java
 *
 * Created on 23. Februar 2005, 10:38
 */

package org.dyndns.widerstand.openplatformmanager;

import org.dyndns.widerstand.OpenPlatform.*;
import javax.swing.*;
import java.io.*;

/**
 *
 * @author  Widerstand
 */
public class PutKeyJPanel extends javax.swing.JPanel {
    
    private MainJFrame parent;
    private String password = new String();
    private SwingUtil swingUtil;
    
    /** Creates new form PutKeyJPanel */
    public PutKeyJPanel(MainJFrame parent) {
        this.parent = parent;
        swingUtil = new SwingUtil();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelKeySetVersion = new javax.swing.JLabel();
        jLabelNewKeySetVersion = new javax.swing.JLabel();
        jTextFieldKeySetVersion = new javax.swing.JTextField();
        jTextFieldNewKeySetVersion = new javax.swing.JTextField();
        jLabelKeyIndex = new javax.swing.JLabel();
        jTextFieldKeyIndex = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3DESKey = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jCheckBox3DESKey = new javax.swing.JCheckBox();
        jPasswordField3DESKey = new javax.swing.JPasswordField();
        jButton3DESKey = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelRSAKey = new javax.swing.JLabel();
        jTextFieldRSAKey = new javax.swing.JTextField();
        jButtonLoadRSAKey = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("Put Key"), new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5))));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jPanel7.setLayout(new java.awt.GridBagLayout());

        jPanel7.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("Key Set Version Parameters"), new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5))));
        jLabelKeySetVersion.setText("Key Set Version");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel7.add(jLabelKeySetVersion, gridBagConstraints);

        jLabelNewKeySetVersion.setText("New Key Set Version");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel7.add(jLabelNewKeySetVersion, gridBagConstraints);

        jTextFieldKeySetVersion.setColumns(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel7.add(jTextFieldKeySetVersion, gridBagConstraints);

        jTextFieldNewKeySetVersion.setColumns(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel7.add(jTextFieldNewKeySetVersion, gridBagConstraints);

        jLabelKeyIndex.setText("Key Index");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel7.add(jLabelKeyIndex, gridBagConstraints);

        jTextFieldKeyIndex.setColumns(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel7.add(jTextFieldKeyIndex, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(jPanel7, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("3DES Key"), new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5))));
        jLabel3DESKey.setText("3DES Key");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel3DESKey, gridBagConstraints);

        jButton3.setText("Put Key");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jButton3, gridBagConstraints);

        jCheckBox3DESKey.setText("Display as Cleartext");
        jCheckBox3DESKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3DESKeyActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jCheckBox3DESKey, gridBagConstraints);

        jPasswordField3DESKey.setColumns(47);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jPasswordField3DESKey, gridBagConstraints);

        jButton3DESKey.setText("Load Key");
        jButton3DESKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3DESKeyActionPerformed(evt);
            }
        });

        jPanel5.add(jButton3DESKey, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(jPanel5, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("RSA Key"), new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5))));
        jLabelRSAKey.setText("RSA Key");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel4.add(jLabelRSAKey, gridBagConstraints);

        jTextFieldRSAKey.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel4.add(jTextFieldRSAKey, gridBagConstraints);

        jButtonLoadRSAKey.setText("Load Key File");
        jButtonLoadRSAKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadRSAKeyActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel4.add(jButtonLoadRSAKey, gridBagConstraints);

        jButton4.setText("Put Key");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jButton4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(jPanel4, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel8);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void jButton3DESKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3DESKeyActionPerformed
        final JFileChooser fc = new JFileChooser();
        int ret = fc.showOpenDialog(this);
        byte _3DESKey[];
        if (ret == JFileChooser.APPROVE_OPTION) {
            try {
                _3DESKey = OPSPUtil.load3DES(fc.getSelectedFile());
                jPasswordField3DESKey.setText(OPSPUtil.toHexString(_3DESKey));
            } catch (IOException e) {
                swingUtil.errorInJComponent(this, jPasswordField3DESKey,
                        e.getMessage(), "I/O Error");
            }
        }
    }//GEN-LAST:event_jButton3DESKeyActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        swingUtil.resetJComponentColor();
        byte[] DESKey;
        try {
            DESKey = OPSPUtil.bytesFromHexString(new String(jPasswordField3DESKey.getPassword()));
        } catch (NumberFormatException e) {
            swingUtil.errorInJComponent(this, jPasswordField3DESKey,
                    "Colored text field cannot be understood as Hex String", "Wrong Number Format");
            return;
        }
        Short dummy;
        byte keySetVersion;
        try {
            dummy = Short.decode(jTextFieldKeySetVersion.getText());
            if (dummy > 255 || dummy < 0) 
                throw new NumberFormatException();
            keySetVersion = dummy.byteValue();
        } catch (NumberFormatException e) {
            swingUtil.errorInJComponent(this, jTextFieldKeySetVersion,
                    "Colored text field cannot be understood as Number", "Wrong Number Format");
            return;
        }
        byte keyIndex;
        try {
            dummy = Short.decode(jTextFieldKeyIndex.getText());
            if (dummy > 255 || dummy < 0) 
                throw new NumberFormatException();
            keyIndex = dummy.byteValue();
        } catch (NumberFormatException e) {
            swingUtil.errorInJComponent(this, jTextFieldKeyIndex,
                    "Colored text field cannot be understood as Number", "Wrong Number Format");
            return;
        }
        byte newKeySetVersion;
        try {
            newKeySetVersion = Byte.decode(jTextFieldNewKeySetVersion.getText());
        } catch (NumberFormatException e) {
            swingUtil.errorInJComponent(this, jTextFieldNewKeySetVersion,
                    "Colored text field cannot be understood as Number", "Wrong Number Format");
            return;
        }
        try {
            OPSPWrapper.put3desKey(parent.session.cardHandle, parent.session.secInfo,
                    parent.session.cardInfo, keySetVersion, keyIndex, newKeySetVersion, DESKey, parent.session.kekKey);
        } catch (OPSPException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Open Platform Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Put 3DES Key.", "Open Platform Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButtonLoadRSAKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadRSAKeyActionPerformed
        final JFileChooser fc = new JFileChooser();
        int ret = fc.showOpenDialog(this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTextFieldRSAKey.setText(file.getAbsolutePath());
            password = PasswordJDialog.showDialog(parent);
        } else {
            password = new String();
        }
    }//GEN-LAST:event_jButtonLoadRSAKeyActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        swingUtil.resetJComponentColor();
        byte keySetVersion;
        try {
            keySetVersion = Byte.decode(jTextFieldKeySetVersion.getText());
        } catch (NumberFormatException e) {
            swingUtil.errorInJComponent(this, jTextFieldKeySetVersion,
                    "Colored text field cannot be understood as Number", "Wrong Number Format");
            return;
        }
        byte newKeySetVersion;
        try {
            newKeySetVersion = Byte.decode(jTextFieldNewKeySetVersion.getText());
        } catch (NumberFormatException e) {
            swingUtil.errorInJComponent(this, jTextFieldNewKeySetVersion,
                    "Colored text field cannot be understood as Number", "Wrong Number Format");
            return;
        }
        byte keyIndex;
        try {
            keyIndex = Byte.decode(jTextFieldKeyIndex.getText());
        } catch (NumberFormatException e) {
            swingUtil.errorInJComponent(this, jTextFieldKeyIndex,
                    "Colored text field cannot be understood as Number", "Wrong Number Format");
            return;
        }
        try {
            OPSPWrapper.putRsaKey(parent.session.cardHandle, parent.session.secInfo,
                    parent.session.cardInfo, keySetVersion, keyIndex, newKeySetVersion,
                    jTextFieldRSAKey.getText(), password);
        } catch (OPSPException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Open Platform Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Put RSA Key.", "Open Platform Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jCheckBox3DESKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3DESKeyActionPerformed
        if (jCheckBox3DESKey.isSelected())
            jPasswordField3DESKey.setEchoChar('\0');
        else
            jPasswordField3DESKey.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox3DESKeyActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3DESKey;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonLoadRSAKey;
    private javax.swing.JCheckBox jCheckBox3DESKey;
    private javax.swing.JLabel jLabel3DESKey;
    private javax.swing.JLabel jLabelKeyIndex;
    private javax.swing.JLabel jLabelKeySetVersion;
    private javax.swing.JLabel jLabelNewKeySetVersion;
    private javax.swing.JLabel jLabelRSAKey;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField3DESKey;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldKeyIndex;
    private javax.swing.JTextField jTextFieldKeySetVersion;
    private javax.swing.JTextField jTextFieldNewKeySetVersion;
    private javax.swing.JTextField jTextFieldRSAKey;
    // End of variables declaration//GEN-END:variables
    
}
