/*
 * SideJPanel.java
 *
 * Created on 18. Februar 2005, 01:14
 */

package org.dyndns.widerstand.openplatformmanager;
import javax.swing.tree.*;
import javax.swing.*;
import java.awt.Component;

/**
 *
 * @author  Widerstand
 */
public class SideJPanel extends javax.swing.JPanel {
    
    private SessionInformation session;
    private MainJFrame main;
    
    /** Creates new form SideJPanel */
    public SideJPanel(SessionInformation session, MainJFrame main) {
        this.main = main;
        this.session = session;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new OPSPJTree(session, main);

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTree1);

        add(jScrollPane1, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    
}
