.\" Process this file with
.\" groff -man -Tascii gpshell.1
.\"
.TH GPSHELL 1 "MARCH 2010" Linux "User Manuals"
.SH NAME
gpshell \- command line tool for the management of GlobalPlatform compliant smart cards
.SH SYNOPSIS
.B gpshell [
.I scriptfile
.B ]
.SH DESCRIPTION
.B gpshell
gpshell can manage applications on smart cards supporting the GlobalPlatform.
This comprises the installation and deletion of applications, getting the
applications status and card data. These appications are practical always Java Card applets.
Additional key management commands are provided.

The most common way to use gpshell is a scriptfile. But it is also possible to read the commands from stdin.
.SH COMMANDS
.IP mode_201
Set protocol mode to OpenPlatform 2.0.1
.IP mode_211
Set protocol mode to GlobalPlatform 2.1.1
.IP visa_key_derivation
If you have a card which uses the VISA key derivation scheme for the key calculation,
like GemXpresso Pro or some JCOP cards you must set this.
.IP  emv_cps11_key_derivation
If you have a card which uses the EMV CPS 1.1 key derivation scheme for the key calculation, like a Sm@rtCafe Expert 3.0 you must set this.
.IP enable_trace
Enable APDU trace

You will see the sent APDUs in clear text. The last two bytes of the
reponse are the response code. A reponse code of 9000 means success,
otherwise the response code indicates an error. This may be OK when
deleting a non existing applet or package.
.IP enable_timer
Enables the logging of the execution time of a command.
.IP establish_context
Establish context
.IP card_connect
.I "-reader readerName"
Connect to card in the reader with readerName
.IP card_connect
.I "-readerNumber x"
Connect to card in the xth reader in the system
.IP open_sc
.I "-keyind x -keyver x -key xyz -mac_key xyz -enc_key xyz -kek_key xyz -security x -scp x -scpimpl x"
Open secure channel

For OpenPlatform 2.0.1' card only -keyind -keyver -mac_key and enc_key are necessary.
If you have an card which uses the VISA key derivation scheme, like a GemXpresso Pro or some JCOP cards,
set visa_key_derivation and you MUST specify with -key the master (mother) key. -mac_key and -enc_key are not relevant.
For GlobalPlatform 2.1.1 cards -scp and -scpimpl should be not necessary to supply. You must also specify -kek_key.
If your card supports a Secure Channel Protocol Implementation with only one base key, specify this key with -key and omit the others.
.IP select
.I "-AID AID"
Select AID instance
.IP install
.I "-file appletFile -priv privilege -sdAID sdAID -AID AIDInPkg -pkgAID packageAID -instAID instanceAID -nvCodeLimit x -nvDataLimit x"
Load and installs in one step

The parameters -AID -instAID -pkgAID -nvCodeLimit can be detected automatically and the -AID and -instAID is set to the first applet in appletfile.

For the sdAID the AID selected with the select command is chosen if not given. Otherwise the default Card Manager / Security Issuer Domain AID is chosen. So usually you do not have to pass it.
.IP install_for_load
.I "-pkgAID x -sdAID sdAID -nvCodeLimit y"
Install for Load

For the sdAID the AID selected with the select command is chosen if not given. Otherwise the default Card Manager / Security Issuer Domain AID is chosen. So usually you do not have to pass it.
You may need to use this command if the combined install command does not work.
.IP load
.I "-file appletFile"
Load applet

You may need to use this command if the combined install command does not work.
.IP install_for_install
.I "-priv privilege -AID AIDInPkg -pkgAID pkgAID -instAID instanceAID -nvDataLimit x"
Instantiate applet

You may need to use this command if the combined install command does not work. Or you want to install a preinstalled Security Domain.
.IP card_disconnect
Disconnect card
.IP get_status
.RS
.I "-element e0"
List applets and packages and security domains
.RE
.RS
.I "-element 20"
List packages
.RE
.RS
.I "-element 40"
List applets or security domains
.RE
.RS
.I "-element 80"
List Card Manager / Security Issuer Domain
.RE
.IP release_context
Release context
.IP put_sc_key
.I "-keyver 0 -newkeyver 2 -mac_key new_MAC_key -enc_key new_ENC_key -kek_key new_KEK_key -cur_kek current_KEK_key"
Add new key set version 2
.IP put_sc_key
.I "-keyver 1 -newkeyver 1 -mac_key new_MAC_key -enc_key new_ENC_key -kek_key new_KEK_key -cur_kek current_KEK_key"
Replace key set version 1
.IP put_dm_keys
.I "-keyver 0 -newkeyver 2 -file public_rsa_key_file -pass password -key new_receipt_generation_key"
Put delegated management keys for GP 2.1.1 in version 2
.IP put_dm_keys
.I "-keyver 0 -newkeyver 2 -file public_rsa_key_file -pass password -key new_receipt_generation_key -cur_kek current_KEK_key"
Put delegated management keys for OP 2.0.1' in version 2
.IP send_apdu
.I "-sc 0 -APDU xxx"
Send APDU xxx without secure channel

The APDU is given as hex without spaces and without leadings 0x.
.IP send_apdu_nostop
.I "-sc 0 -APDU xxx"
Does not stop in case of an error

The APDU is given as hex without spaces and without leadings 0x.
.IP get_data
.I "-identifier identifier"
A GET DATA command returning the data for the given identifier.
.SH OPTIONS
.IP -keyind
.I x
Key index x
.IP -keyver
.I x
Key set version x
.IP -newkeyver
.I x
New key set version x
.IP -key
.I key
Key value in hex
.IP -mac_key
.I key
MAC key value in hex
.IP -enc_key
.I key
ENC key value in hex
.IP -kek_key
.I key
KEK key value in hex
.IP -security
.I x
0: clear, 1: MAC, 3: MAC+ENC
.IP -reader
.I readerName
Smart card reader name
.IP -readerNumber
.I x
Number of the reader in the system to connect to.
If -reader is given this is ignored.
.IP -protocol
.I x
Protocol, 0:T=0, 1:T=1
Should not be necessary to be stated explicitly.
.IP -AID
.I aid
Applet ID
.IP -sdAID
.I aid
Security Domain AID
.IP -pkgAID
.I aid
Package AID
.IP -instAID
.I aid
Instance AID
.IP -nvCodeLimit
.I x
Non-volatile code size limit
.IP -nvDataLimit
.I x
Non-volatile data size limit
.IP -vDataLimit
.I x
Volatile data size limit
.IP -file
.I name
File name
.IP -instParam
.I param
Installation parameter
.IP -element
.I x
Element type to be listed in hex
.RS
80 - Card Manager / Card Issuer Security Domain only.
.RE
.RS
40 - Applications (and Security Domains only in GP211).
.RE
.RS
20 - Executable Load Files only.
.RE
.RS
10 - Executable Load Files and their Executable Modules only (Only GP211)
.RE
.IP -sc
.I x
Secure Channel mode (0 off, 1 on)
.IP -APDU
.I apdu
APDU to be sent. Must be in hex format, e.g. 80CA00CF00.
.IP -priv
.I x
Privilege. E.g. 0x04 Default Selected
.IP -scp
.I x
Secure Channel Protocol (1 SCP01, 2 SCP02, default no set).
Should not be necessary to be stated explicitly.
.IP -scpimpl
.I x
Secure Channel Implementation (default not set)
Should not be necessary to be stated explicitly.
.IP -pass
.I password
Password for key decryption
.IP -identifier
.I identifier
Identifer for the tag for the get_data command. Must be in hex format, e.g. 9F7F.
.SH ENVIRONMENT
.IP GLOBALPLATFORM_DEBUG
Enables debugging output from the underlying GlobalPlatform library.
.IP GLOBALPLATFORM_LOGFILE
Sets the log file name for the debugging output.
.SH Key Derivation
.IP VISA
For the VISA key derivation scheme, like used in a GemXpresso Pro or some JCOP cards, set visa_key_derivation
.IP "EMV CPS 1.1 / CDK (CPG 2.04)"
For the key derivation according to EMV CPS 1.1 / CDK (CPG 2.04), like Sm@rtCafe Expert 3.0, set emv_cps11_key_derivation.

Known unsupported key derivation schemes are:
.IP "CDK (CPG 2.02)"
.IP ISK(D)
.SH BUGS
.IP "JCOP 10"
install_for_load fails for unknown reason, so nothing can be installed.
.SH AUTHOR
Karsten Ohme <k_o_@users.sourceforge.net>

